version: 2
updates:
  - package-ecosystem: nuget
    directory: "/backend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/backend/Identity/src/AcingIU.Identity.Api"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/backend/DeviceTrust/src/AcingIU.DeviceTrust.Api"
    schedule:
      interval: weekly
