param(
  [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
  [string]$Inventory = (Join-Path $Root "docs/security/ISSUE_63_CLAIM_OCCURRENCE_INVENTORY.json"),
  [string]$Register = (Join-Path $Root "docs/security/ISSUE_63_CAPABILITY_EVIDENCE_REGISTER.json")
)
$ErrorActionPreference="Stop"
if(!(Test-Path $Inventory)){throw "Missing occurrence inventory: $Inventory"}; if(!(Test-Path $Register)){throw "Missing capability register: $Register"}
$inv=Get-Content $Inventory -Raw|ConvertFrom-Json; $reg=Get-Content $Register -Raw|ConvertFrom-Json
$caps=@{}; foreach($c in @($reg.capabilities)) { if([string]::IsNullOrWhiteSpace([string]$c.id)){throw "Capability missing id."}; if($caps.ContainsKey($c.id)){throw "Duplicate capability id: $($c.id)"}; $caps[$c.id]=$c; foreach($f in @("claim","surface","status","evidence","automatedTest","owner","supportedDeviceScope","limitation")){if([string]::IsNullOrWhiteSpace([string]$c.$f)){throw "Capability $($c.id) missing ${f}."}}; if([string]$c.status -match "(?i)^verified$"){throw "Verified capability is not permitted: $($c.id)"}; $testPath=([string]$c.automatedTest -split "::")[0]; if(!(Test-Path (Join-Path $Root $testPath))){throw "Capability $($c.id) test reference missing: $($c.automatedTest)"} }
if(!$caps.ContainsKey("CAP-016")){throw "Authorized Device Lab capability missing."}; if($caps["CAP-016"].status -ne "Planned"){throw "Authorized Device Lab must remain Planned."}
$valid=@("verified","implemented but unverified","simulator","planned","external dependency","prohibited/removed","historical evidence","test fixture","lint-rule definition","false positive","host permission","educational/non-operational","disabled pending validation")
foreach($o in @($inv.occurrences)) { foreach($f in @("occurrenceId","file","line","normalizedTerm","context","classification","capabilityId","evidenceRef","rationale","reviewStatus")){if([string]::IsNullOrWhiteSpace([string]$o.$f)){throw "Occurrence missing ${f}: $($o.occurrenceId)"}}; if(!$caps.ContainsKey($o.capabilityId)){throw "Occurrence $($o.occurrenceId) references unknown capability $($o.capabilityId)."}; if($valid -notcontains $o.classification){throw "Occurrence $($o.occurrenceId) has invalid classification $($o.classification)."}; if($o.classification -eq "verified"){throw "Verified occurrence is not permitted: $($o.occurrenceId)"}; if(!(Test-Path (Join-Path $Root $o.file))){throw "Occurrence file missing: $($o.file)"}; if([int]$o.line -lt 1){throw "Occurrence line invalid: $($o.occurrenceId)"} }
$tracked=@((& git -C $Root ls-files)|Where-Object {$_}); if(([int]$inv.includedFileCount+@($inv.exclusions).Count) -ne $tracked.Count){throw "Inventory file accounting mismatch: tracked=$($tracked.Count) included=$($inv.includedFileCount) excluded=$(@($inv.exclusions).Count)"}
Write-Output ("Structured security-claims validation passed: capabilities="+$caps.Count+" occurrences="+@($inv.occurrences).Count+" trackedFiles="+$tracked.Count+" excludedFiles="+@($inv.exclusions).Count)
